[project]
name = "dwcom"
version = "0.1.0"
description = "A trigger that adds several features to the TeamTalk commander."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cyal>=0.4.5",
    "notify-py>=0.3.43",
    "ntfpy>=0.0.12",
    "prismatoid>=0.16",
    "pyprowl>=3.0.1",
    "soundfile>=0.13.1",
    "watchdog>=6.0.0",
]


